### ISSUE TITLE
请问在论文中为什么没采用全部数据？

### ISSUE THREAD

**Issue by dqksnow** [yaqingwang/WeFEND-AAAI20#3]
论文的Table1里列出的数据数量明显少于您在这里公布的数据数量，且比值Avg. Reports/News远高于论文中的值。请问论文中筛选数据的依据是什么？

**Comment by yaqingwang** [comment]
> 论文的Table1里列出的数据数量明显少于您在这里公布的数据数量，且比值Avg. Reports/News远高于论文中的值。请问论文中筛选数据的依据是什么？

We did not do data selection. The labeling job is streaming and thus we have annotated more data after the submission.
